version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - redis
    command: ["flask", "run", "--host=0.0.0.0", "--port=3000", "--reload"]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"